# Generated by Django 5.2.4 on 2025-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.category'),
        ),
    ]
